export const buttons = [
    {symbol: '1', operation: ''},
    {symbol: '2', operation: ''},
    {symbol: '3', operation: ''},
    {symbol: '+', operation: 'sum'},
    {symbol: '4', operation: ''},
    {symbol: '5', operation: ''},
    {symbol: '6', operation: ''},
    {symbol: '-', operation: 'subtract'},
    {symbol: '7', operation: ''},
    {symbol: '8', operation: ''},
    {symbol: '9', operation: ''},
    {symbol: '*', operation: 'multiply'},
    {symbol: 'C', operation: 'clear'},
    {symbol: '0', operation: ''},
    {symbol: '=', operation: 'equal'},
    {symbol: '/', operation: 'division'},
];