export const ADD_CHAR = 'ADD_CHAR';
export const REMEMBER_NUMBER_AND_OPERATION = 'REMEMBER_NUMBER_AND_OPERATION';
export const CLEAR = 'CLEAR';
export const CLEAR_CURRENT_NUMBER = 'CLEAR_CURRENT_NUMBER';
export const CLEAR_MEMORY = 'CLEAR_MEMORY';